### ISSUE TITLE
The ELK container failed to start on arm64 linux, due to elk_docker_image: sebp/elk:8.9.1 has no arm64 image

### ISSUE THREAD

**Issue by zhangcheng** [SlingNode/slingnode-ansible-ethereum-observability#24]
```
> docker logs elk
exec /usr/local/bin/start.sh: exec format error
```

I guess this is a caveat for people like me trying to run on arm64 linux. All other images in use have arm64 version except this one, which prevents from using arm64 linux for monitoring server.

**Comment by pgjavier** [comment]
Currently we do not support arm but we'll gladly accept contributions.
